server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    location / {
        return 301 /web/index.html;
    }

    location /web/ {
        try_files $uri $uri/ /web/index.html;
    }
    location /admin/{
        try_files $uri $uri/ /admin/index.html;
    }
    location /assets/ {
        try_files $uri =404;
    }
}
